---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secret
  namespace: main
spec:
  encryptedData:
    JWT_EXPIRES_IN: AgCJdRE2EKLeDk8Ym7AeaTQoWpuFC57gPK4EJn42AcceZNcoXC4Zv6tzR7hYP19IF/XP6M3NwOmuO4/rfhMA3UvYJXJI8itY+0zWlp7vkORGGVDfYgadFUUgwvPaqpMFxatpXiGFoQEC/7ynirRiQKM08chRHoZHOmCypd92zTE/BEPncsJjmz7nnZgFE2KnU7t2KwOBFaVwCZiXL+QhLVrg/kHwK/KT6zgi4IatGAKLTtWm4CD9FUDfX4LEPMh/7x6ZpHtnaHIEXUPiBiay3S/C/mSsOj7Vb4oFL7MMa1XskkuXEJuUw134Vj5k16lJ4XfKLc40QsF5+wRAPVC4sK1TtVi0R7YW9sG/zfNp2kWSc8yTkoZ5RcLa8R3cH90WveJJYBq/GIr0HFomscUyHn9UNJNyjkzg/Y7HfLxlrMsAhtuPwO5nn6GCTmTc5yufSW6XzcXv3ql8Gg1ZOXkma/UVupaZyYQ5Tr8bNSFOVZyOCvhdpvLN9qSEQXNHhlvucCxRtjX5/o+57rkrqoJo51bjd6Bw7ApPpaRRddX535JpjJf4TU/jUqWjf2mlzfMsCWH5YGngx0fok+lORSyiOYewgmoe3BOULEEmBdecMhnLdGw4WDwJOMuefKSO031Hc8IWNZKvCFmTUpVn5f3RPGuUTWNTxY4oUPxE4izTXo86PioHHl503qCxBJG+PkE57IfO4Eo=
    JWT_SECRET: AgA8DAeAeZ/EZHjNodplDOInHagR+/0oT/xHFGCCI5gWNZBh2NXa9LogMZu+TDK+udFfNS3FEFRMicwmbIeThzUytg2MPx4samU8Hqhv9zXYLHstsmiuvabNGvs/0aGcb9zkS4ZJKPESKeqFcUUIelzbPRSjbNTsx1WC/Y8m51wLKc7YmC1NNA2ByrJjimnll9byG86lcXu7WTHncnmo3GqcFpgZM31Psa+YDQ5izxch/6Uyo5BXAD34/rrluP9w9+zxuQeiy/NwO5AEqWMTUquqNYayYHe+TVnSqkjnNsxGRQ6StXetNqVtWyUhCoq/1rNNySBqZTyMDTbQNHQJZPpmlo9TopDdxA0vyf40mjkKZad4POdQudS/HqabSC+x+TdDYXvQoOo4FWDdj+CtFSc/c5f4Tu/SzVkcKxXhfxzhuf6r+i+6g9gWXzsU6VXRL0X9z56wTXQEOT2SDrM/6eDKFsl4f3UUHh4fCREs9E/oH97b98yM1ID7UF0wgZKm/ptD4+gX7+TbH0oTgPQIsO09S8UIcMFABWpf5JX8FVUFkO3mrsD3yicw7eUonfcWE01BXV8IYbLoFFJD3VphyWf+aGe38XYGyj+rlasiAXP6emCCUUQLuaKSrsjeA9uzVGTbzGJ4bE53qJ5fzFvKzn/Cey8+9Y7sEoI15mqGBMcSQImIc/eg+iBbG+9ty70p1qqZ5lTjIslom7TpEvgQICg9hbk5OtJtBKhcNX9JwMlXqbz3RaUcRezXTjGpauf1m01lqFc=
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secret
      namespace: main
    type: Opaque
