apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  JWT_SECRET: {{ index .Values "Vastra-user-service" "env" "JWT_SECRET" | b64enc | quote }}
  # Password matched to global postgresql config
  DB_PASSWORD: {{ "postgrespassword" | b64enc | quote }}
