{{- $dbs := dict "users-db" .Values.usersDb "products-db" .Values.productsDb "orders-db" .Values.ordersDb }}
{{- range $dbName, $dbConfig := $dbs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $dbName }}-config
data:
  POSTGRES_DB: {{ $dbConfig.name | quote }}
  POSTGRES_USER: {{ $dbConfig.user | quote }}
---
{{- end }}
