apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.Vastra-order-service.env.JWT_SECRET | b64enc | quote }}
  DB_PASSWORD: {{ "postgrespassword" | b64enc | quote }}
