{{- $dbs := dict "users-db" .Values.usersDb "products-db" .Values.productsDb "orders-db" .Values.ordersDb }}
{{- range $dbName, $dbConfig := $dbs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbName }}-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ $dbConfig.password | b64enc | quote }}
---
{{- end }}
