apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        envFrom:
        - configMapRef:
            name: frontend-service-config
        ports:
        - containerPort: {{ .Values.port | default 80 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port | default 80 }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port | default 80 }}
          initialDelaySeconds: 5
          periodSeconds: 5
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
