apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port | default 80 }}
    targetPort: {{ .Values.port | default 80 }}
  selector:
    app: frontend-service
