---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: dev
spec:
  encryptedData:
    JWT_EXPIRES_IN: AgCp4xJJ1oVHkSsRpVpJ0C5KJ07SqD6P6lwrBt37DUrXzRBf3O7D2nP6UoMD7+CeuR+g72WVoBSpMO/bsHurLAkitLZ7NucAyq9fvtBKKrvo05ppHV8J8bmRkvNGVFMSl5MtF+2RQx62hjGob9DsxMh76nHUuo5r/dV7sNiVP6tdIKJkuucO7SupZZDQuOJVL5zrTdIh8yyM6PoHuBJIwdIozYH6RqGfxa1U7K2b+DEqkQqEc5DhJCHlyotLR4oW1r+BCLx+0wOp2MXB1l7cYDlhZvKC79C5ONE99AIA1DQZYlvgQEmSuHrdjuyAauVJ9oXr350QPbPfr9O8xIzg8xTSqBUNDNeX1OEQN57Nk5dAV/mPXh+4VoGTP4lgHWjQydm771U/qkLl6BaIJ9Z9IC5reCNXqLzRRfy+4/N1v/1S87fX4w+sqm957m49NIT03L0I0uSPE6JCFQlp+OAQo9VyITUIK0Vudra99cUReP4RTiDNfi36RWzyyOqmRdlVL6WOKFc8qE74vDb3SuU1h4Qs0c/XIfX1TH41G/WqyfP4eFu2QtifXXWRdEAAfTJwdLhtxboltGNWhBz8NQnAf5jWTaAc1S8BDQa15poCfFEY9JvMWwRUkAwUXXtFPwUuchPjUQ0jUs0ck/xhod5GN7w+UeSgDouLCV7cdc8amn0jpWd7NeZ4S8E3I38E1MTKutMsXVU=
    JWT_SECRET: AgCfSNDb9PYBLJhaY/HGmvr12MgXyQNeqhO5MhpgWSzrARWzTslHxc3BvxjmGvBKfKRA1KvVp3udqJ6I25HPDieCuw0+LJyobG2SnzZahFs9Yzu8S0/pGOpg9Wfjx9zRUImgt1u6cqpHUY997co0ZWXKL38T8vxZEnjmoDyQZgyKwzIXN0D36VUKdOX75kNod+QIxHP2tYUzr947k3ufcXxQFJWU5L89j2VPyYxI5jXv+4kFbT4rkROx1oblr3MyAL5Kq56vBtuaJIibESMXZiqS5PBXWGxhBNpfhimuend6ttdI/30HvcN6oXift1drARwo9AJet59rDzztroiJI0c8XBJu4bjhg1U/3IaDmPyi8cZkIltewCvmaCnq/YjSngJ7BvSZm2rJGdbtB/wHd/NoHXkM8dog6We2iMkzaE2R+9F+2/LnfqklxIO368pEQq+wnvJPoeUzz1PADBb4zuaUYJotB0fI7zQnCAMyn/qP8wVFCPHSmzfiiEoqNQvKWIuh6OWdAak7LrPrWrtslqPVdxXc9+AXgAJNjEWz5JMB6of/Z2oIaHVgi5If58TiWIeJ9h+qW1H2zjB15AyGqINdfaMHHHuGcxnC6LPCvAF/24YBg98cMv9Ln4mf8EizR+rUIKyihRTA1oyE2BzlMZ2pSRbq40nXpCUCFd9qVNeDQdB/H/sJ4cKvQzpNo3YtzMt2BKLmSyn82xzlrLKixQj1gt9aF63mllxphwhbfWXjphUJhauI+MxWgjIEgpjONM6VbXI=
  template:
    metadata:
      name: jwt-secret
      namespace: dev
    type: Opaque
