---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vastra-secrets-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vastra
  source:
    repoURL: https://github.com/Harshitha3826/Vastra-helm.git
    targetRevision: HEAD
    path: vastra-deployments/secrets/main
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
