apiVersion: v2
name: vastra-deployments
description: VastraCo microservices e-commerce application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: envoy-gateway
    repository: file://charts/envoy-gateway
  - name: postgresql
    repository: file://charts/postgresql
  - name: Vastra-user-service
    repository: file://charts/Vastra-user-service
  - name: Vastra-product-service
    repository: file://charts/Vastra-product-service
  - name: Vastra-order-service
    repository: file://charts/Vastra-order-service
  - name: frontend
    repository: file://charts/frontend